name: plantea
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutterflow_ui : 0.2.0+1
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  barcode_widget: 2.0.3
  cached_network_image: 3.2.1
  carousel_slider: 4.2.1
  collection:
  emoji_flag_converter: 1.1.0
  equatable: 2.0.5
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_credit_card: 3.0.6
  flutter_plugin_android_lifecycle: 2.0.9
  flutter_staggered_grid_view: 0.6.2
  font_awesome_flutter: 10.1.0
  fl_chart: 0.55.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  intl: 0.18.1
  json_path:
  mime_type: 1.0.0
  page_transition: 2.0.4
  percent_indicator: 4.2.2
  rive: 0.10.3
  rive_common: 0.0.6
  provider: 6.0.4
  smooth_page_indicator: 1.0.1
  sqflite: 2.2.6
  swipeable_card_stack: 0.0.5
  timeago: 3.2.2
  table_calendar: 3.0.9



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_lints: 3.0.0
  lints: 3.0.0
  

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/logo.jpg